{
	"version": 1699523585,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/ship-sheet0.png",
		"images/wall-sheet0.png",
		"images/planet-sheet0.png",
		"images/planet-sheet1.png",
		"images/ship_smoke-sheet0.png",
		"images/particles.png",
		"images/side-sheet0.png",
		"images/spikes-sheet0.png",
		"images/electric-sheet0.png",
		"images/star-sheet0.png",
		"images/star-sheet1.png",
		"images/star-sheet2.png",
		"images/reward-sheet0.png",
		"images/gametitle-sheet0.png",
		"images/spritefont_score.png",
		"images/play-sheet0.png",
		"images/highscore-sheet0.png",
		"images/highscore-sheet1.png",
		"images/spritefont_gamescore.png",
		"images/volume-sheet0.png",
		"images/volume-sheet1.png",
		"media/arc-welding-spark-sounds.m4a",
		"media/arc-welding-spark-sounds.ogg",
		"media/sucsess.m4a",
		"media/sucsess.ogg",
		"media/cyberexplode.m4a",
		"media/cyberexplode.ogg",
		"media/pop gp 002.m4a",
		"media/pop gp 002.ogg",
		"media/pop menu 002.m4a",
		"media/pop menu 002.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}